### ISSUE TITLE
Plugin should add `utilities` instead of `components`

### ISSUE THREAD

**Issue by f15u** [mrcaidev/tailwindcss-radix-colors#15]
Working on #14, I noticed that classes are added `components` instead of `utilities`.

As [stated in the official tailwind docs](https://tailwindcss.com/docs/plugins#adding-components), components should be used for, citing, "[...] opinionated, complex classes like buttons, form controls, alerts, etc [...]".

I think we should reflect that.

This is a breaking change because people could not be using `@tailwind utilities` layer in their css and the build would fail.
On the other hand not using `@tailwind components` the plugin is not going to work as expected like in our project.

**Comment by mrcaidev** [comment]
I agree that these semantic classes are not quite opinionated like `components`. But I also think they have gone beyond `utilities`, since they can decide for you the dark mode colors, and even foreground text colors on scale 9.

In my opinion, `utilities` classes should be atomic enough for users to composite them at will. However, these semantic classes are not meant to be composited. On the contrary, they are already the **result** of some kind of composition.

And from the TailwindCSS documentation:

> Use it to add more opinionated, complex classes like buttons, form controls, alerts, etc; the sort of pre-built components you often see in other frameworks that you might need to override with utility classes.

I do think these semantic classes conform to this definition, as there might be a chance that users want to partially override a semantic class with another utility class, like `bg-blue-solid text-red-12`. So in this sense, they are more like `components` IMO, though definitely not as complex as a `btn` class.

Thanks for your suggestion!

**Comment by f15u** [comment]
> [...] I do think these semantic classes conform to this definition, as there might be a chance that users want to partially override a semantic class with another utility class, like `bg-blue-solid text-red-12`. So in this sense, they are more like `components` IMO, though definitely not as complex as a `btn` class. [...]

I understand why it is done that way, and based on your example, I agree with the current approach.

I would suggest keeping this issue open, as other folks may have different perspectives on this topic.

Otherwise, it can be closed since you have provided an answer :ok_hand:

**Comment by mrcaidev** [comment]
I will just close it for now and reopen it if other people bring up this issue again.
