### ISSUE TITLE
Missing color scale warnings

### ISSUE THREAD

**Issue by rbutera** [mrcaidev/tailwindcss-radix-colors#19]
I'm getting the following warnings when building my project:

```
Missing color scale primary.1. In order to generate semantic classes, all 12 scales must be defined. If it is an intended behavior to leave some certain scales undefined, this warning can be safely ignored.
Missing color scale secondary.1. In order to generate semantic classes, all 12 scales must be defined. If it is an intended behavior to leave some certain scales undefined, this warning can be safely ignored.
Missing color scale destructive.1. In order to generate semantic classes, all 12 scales must be defined. If it is an intended behavior to leave some certain scales undefined, this warning can be safely ignored.
Missing color scale muted.1. In order to generate semantic classes, all 12 scales must be defined. If it is an intended behavior to leave some certain scales undefined, this warning can be safely ignored.
Missing color scale accent.1. In order to generate semantic classes, all 12 scales must be defined. If it is an intended behavior to leave some certain scales undefined, this warning can be safely ignored.
Missing color scale popover.1. In order to generate semantic classes, all 12 scales must be defined. If it is an intended behavior to leave some certain scales undefined, this warning can be safely ignored.
Missing color scale card.1. In order to generate semantic classes, all 12 scales must be defined. If it is an intended behavior to leave some certain scales undefined, this warning can be safely ignored.
```

Are these from tailwindcss-radix-colors? If so, how can I define these color scales?

**Comment by mrcaidev** [comment]
Yes, these warnings come from this plugin.

This plugin is trying to generate semantic classes for your custom colors, so that you can use classes such as `bg-primary-app`, `bg-secondary-ui`, etc.

And to make this generation successful, e.g. for `primary`, several requirements need to be met:

- Both `primary` and `primarydark` should be defined in `theme.extend.colors`, so that automatic dark mode can be possible. (e.g. `bg-primary-1 dark:bg-primarydark-1`)
- Both of them should have 12 scales defined (`{ 1: "#123456", 2: "#123456", ..., 12: "#123456" }`), so that component classes are fully generated. I'm working on partial generation now.

So you are seeing this warning because I guess the shape of `primary` object does not meet the requirements, i.e. have scales 1-12. But I also guess you probably don't want to use this feature, as the requirements are high and specific.

Also this feature has some known bugs, which I've fixed in dev branch but not yet merged. And It's not documented yet.

So I guess you can safely ignore these warnings, and use `bg-primary-whatever`.

**Comment by rbutera** [comment]
I see, thank you.

By the way @mrcaidev your latest docs build is broken, I believe:

https://tailwindcss-radix-colors.mrcai.dev/semantic-first and a few other pages are blank now!

![image](https://github.com/mrcaidev/tailwindcss-radix-colors/assets/6047293/02130c48-262f-4b9c-9496-7acc64be8540)

**Comment by mrcaidev** [comment]
Oh... I'll soon look into this. Thanks for the reminder!

**Comment by rbutera** [comment]
@mrcaidev could you please provide guidance as to what scales you should use for secondary, muted, accent, popover and card? I am confused.

**Comment by mrcaidev** [comment]
> @mrcaidev could you please provide guidance as to what scales you should use for secondary, muted, accent, popover and card? I am confused.

Shadcn UI is somewhat different from Radix UI in respect of semantic meanings. Shadcn is built upon [Radix Primitives](https://www.radix-ui.com/primitives), but it doesn't fit well with [Radix Colors](https://www.radix-ui.com/colors). In some ways I would even say they are incompliant. You may want to read [Understanding the scale](https://www.radix-ui.com/colors/docs/palette-composition/understanding-the-scale) to see what they corresponds to, but there is no guaranteed one-to-one relationships.
