### ISSUE TITLE
Feature request: Aliasing and option to not remove existing colors

### ISSUE THREAD

**Issue by RyanTT** [mrcaidev/tailwindcss-radix-colors#20]
It would be great if it was possible to combine the color palette provided by this plugin but also keep the existing palette that Tailwind ships with  by default.

I could imagine this could be achieved by adding a new option `removeTailwindColors` which does as the name implies. If it is set to true, the behavior is as it currently is. It is set to false, the only colors to be removed are the ones that are added through this plugin and that have a conflicting name.

Additionally, it would be great if there was an option to give aliases to color palettes. This way one could alias a color palette, include that custom alias in the `include` array and, if `removeTailwindColors` is also set to false, essentially cherry pick Radix colors to use under an alias name that does not conflict with Tailwind.

**Comment by mrcaidev** [comment]
Thanks for your suggestion! I get the point, but I also think it is a super rare case where one would use Tailwind colors alongside with Radix colors. 🤔

I guess I will keep this issue open for a while, and collect further ideas.

**Comment by olavblj** [comment]
I also need this. Need to remove this package now because we have a code base that already uses tailwind colors

**Comment by mrcaidev** [comment]
I'm preparing to work on it. My plan right now is to add two options.

## Priority

The first option is called `priority`. It has 3 possible values:

1. `no-tailwind`: This is the current behavior. Tailwind colors will be completely wiped out.
2. `radix-first`: This is the option you have kindly suggested. Both Radix and Tailwind colors are preserved, but upon name conflicts, Radix colors will be prioritized.
3. `tailwind-first`: This one is more aggressive. Upon name conflicts, Tailwind colors are preserved.

## Alias

The second option is called `alias`. It is an object, its keys being the original color name and its values being the aliased color name. It tries to give aliases to certain Radix colors, so that:

1. When `priority` is set to `tailwind-first`, these aliased Radix color name could "survive" the override.
2. When `priority` is set to `radix-first`, they "make room" for those Tailwind colors that would otherwise be overridden.

In regard of the `include` and `exclude` option, aliases will be respected, that is, aliased name should be used in these two options.

I would make this an RFC to collect relevant opinions before really getting started.

**Comment by RyanTT** [comment]
This sounds perfect for my use-case. 👍

**Comment by mrcaidev** [comment]
Added support for `priority` and `aliases` in v1.4.0. Have a try and tell me if there is any bug!
